### ISSUE TITLE
(1.16.3) Server crash 

### ISSUE THREAD

**Issue by CorgiZero** [JDKDigital/productive-bees#103]
Playing on TNP Limitless 3, mod version 0.4.1.4, on server.

For context, though it may not be related, this crash was occurring whenever I jumped near an Immersive Engineering windmill. It wasn't happening anywhere else from what I could tell.

I would crash to the main menu while getting a StackOverflowError message. Here's the log.
[latest.log](https://github.com/JDKDigital/productive-bees/files/5434037/latest.log)

And another log snippet that mentions the crash.
[message.txt](https://github.com/JDKDigital/productive-bees/files/5434044/message.txt)

**Comment by JaisDK** [comment]
Does the server crash as well or is it only the client? Can I see the servers debug.log as well?

**Comment by CorgiZero** [comment]
The server crashes as well, brings everyone playing to the main menu. I'm pretty sure i can't access the server logs unfortunately.

**Comment by JaisDK** [comment]
without the server log I can't do much, the error in your log are not causing the crash

**Comment by noncom** [comment]
So we were investigating more on this today. The server crashlog is in the attachment, but it looks like that although the client drops out to the main menu with StackOverflowError and the log that contains a recursive OutOfBoundsException that originates in Productive Bees trying to fill in JER info on trading with villagers (see the log posted by CorgiZero), the **server** crash happens because of a totally different reason.

The server-side crash went away after CorgiZero removed all Feedthough Insulators from Immersive Engineering. Consequently client stopped dropping out as well. Placing the IE insulators back again does not repeat the crash now. It could be that the error gonna start happening again after some time.

So it looks like the server-side error is not related to Productive Bees at all, but Productive Bees or JER enter some infinite loop on client side under these conditions. Since this is not the original cause of the problem, it might be ignored by Productive Bees, probably! (except for maybe adding a failsafe to fix the SOE condition if it's not in JER?)

Server crash log:
[crash.log](https://github.com/JDKDigital/productive-bees/files/5435799/crash.log)

**Comment by JaisDK** [comment]
The IndexOutOfBoundsException should be reported to JER, I see from your log that it's happening from other triggers as well. What I do is trigger a recipe recalculation (RecipesUpdatedEvent) which JEI and JER picks up on and makes them reindex the recipe manager. I don't call anything in JER directly.

**Comment by noncom** [comment]
Got it! Thanks for the info! Will report to JER.
