### ISSUE TITLE
crash in bumblezone - not sure if it's your or bumbles end

### ISSUE THREAD

**Issue by mahjerion** [JDKDigital/productive-bees#121]
https://wklej.spigot.pl/#/MABN0MW_kf2af7e6XAv8I8z_1ZwAFohR6D2gonSZdacjbA

https://wklej.spigot.pl/#/MABzeb0IG9Jrg4j6ijq5fllvJ7kkiE6bzD-TL7Ke0hWvxw

Not really sure, has to do with bee bomb. Lemme know if it's solvable or if I should disable anything!

**Comment by JaisDK** [comment]
It's an issue in Bumblezone unfortunately. It looks like they are counting any entity that contains "bee" in the name as a spawnable bee. 
Since they are not updating the mod for  1.15 anymore, the only fix is to disable PB bee spawning, the option is called `spawnProductiveBeesBeesMob`

It wont hurt to do that anyway, since the entities spawned are not the correct ones anyway.

**Comment by mahjerion** [comment]
thanks, ive come up with a roundabout solution for this
