### ISSUE TITLE
Stack overflow error on server

### ISSUE THREAD

**Issue by Water-Cat1** [JDKDigital/productive-bees#141]
Been running this on a server. Player mentioned he blocked the entrance to his hives, and while it was fine for a while, eventually the sever crashed with a stack overflow error, and continued to crash on restart.

[bee crash.txt](https://github.com/JDKDigital/productive-bees/files/5825658/bee.crash.txt)

**Comment by JaisDK** [comment]
Hi, you need to update the mod. This issue was a bug when a bee would exit near fire. Once you update and get into the server you will find the bee has been duplicated a few hundred times so you'll probably have to do a kill command on that bee type.
Let me know which bee it is and I'll get you the command.

**Comment by Water-Cat1** [comment]
Ok, thanks for the explanation! We should be ok, we disabled the mod to get the server going again so we should be fine without the kill command.
