### ISSUE TITLE
Bees leaving 

### ISSUE THREAD

**Issue by Gkjad** [JDKDigital/productive-bees#142]
Bees (vanilla) are leaving the Advanced Beehive with expansion box i think they was still there when i haven't got any boxes
they just went for a trip ` 50 blocks away from my base

**Comment by JaisDK** [comment]
Which version of the mod are you running? A couple of versions ago I fixed a problem where a hive with expansion box would forget that it has 5 available spaces and revert to 3 when unloaded. You'll need to right click the hive block to make it recalculate the space.

**Comment by Gkjad** [comment]
The latest + I found that the "compass" works only once and if you stand in front of some nest that the locator is seeking it shows the arrow to back

**Comment by JaisDK** [comment]
Found out the problem, there had been a compile problem with that version. A new one has been uploaded.

The nest locator is a little tricky and in need of a rewrite, but what do you mean it works only once? You need to tune it to a type of nest and then keep right clicking as you travel for it to search near you for a nest.

**Comment by ghost** [comment]
> ... if you stand in front of some nest that the locator is seeking it shows the arrow to back.

This is happening for me as well, on version 0.6.9.11. I think the problem is in [src/main/resources/assets/productivebees/models/item/nest_locator](https://github.com/JDKDigital/productive-bees/tree/5839c4e0fe1555e5f3831686f07b44cd3e730dd3/src/main/resources/assets/productivebees/models/item/nest_locator). File **"16.json"** is missing. [16.png](https://github.com/JDKDigital/productive-bees/blob/dev-1.16.5/src/main/resources/assets/productivebees/textures/item/nest_locator/16.png) is the forward-pointing image. That image never appears for me when playing.

I can log this as a new bug if that would help matters. Thanks for the mod.

**Comment by ghost** [comment]
Created #188 since the problem isn't related to this bug.
