### ISSUE TITLE
Stopping Zombie/Skeleton Bee's

### ISSUE THREAD

**Issue by mouse0270** [JDKDigital/productive-bees#15]
We are having an issue with these two zombies. The hive is in a 5x5 space that stands 3 blocks tall. It has an expansion hive on it. We have glow stone above and below the hive. The lowest block level light is 9. We even over breed the diamond bees so we had 7 instead of 5. Yes now all of our diamond bees our outside of their hive except 2 because there are 3 skeleton bees inside of it.

How can we prevent Zombie and Skeleton bees from spawning taking up a hives spots? Are we doing something wrong? Like is light level 9 to low?

**Comment by JaisDK** [comment]
As of 0.1.3 the light level at the position of the hive have to be 7 or below to spawn an undead bee. Previous versions had no light requirement. Maybe I need to check the light level in front of the hive instead and also not consider a hive as having space just because bees are out to get pollen. I'll ook into that.
Skeletal and Zombie bees leave the hives at night, so you could catch them when they are out to get rid of them.

**Comment by JaisDK** [comment]
Light level cannot be calculated on the block, it has to be in front of it.

**Comment by mouse0270** [comment]
So this is a bug, because we were using 0.1.4 and still having this issue even though no where near the hive had a light level less than 9
