### ISSUE TITLE
[BUG] [1.18.1] Bees will leave the hive and immediately reenter repeating

### ISSUE THREAD

**Issue by iteathen** [JDKDigital/productive-bees#248]
productivebees-1.18.1-0.8.0.7

Forgive me if this was addressed in a more recent version. I didn't take to the time to create a test environment. Bees will leave the hive and immediate reenter hive every few seconds. This behavior occurs only under certain circumstances. To reproduce, obtain a bee in one dimension/level then transport it to another dimension that does not share weather properties and/or day/night cycles with its birth dimension/level, I used compact machine world for this but the nether might also have the same problem. Now whenever it is raining or night time in the birth dimension/level the bee will exit the hive and immediately reenter the hive every few seconds regardless of the conditions in its actual dimension/level. I suspect that the level property is set in a constructor somewhere and is not updated when the bee is transported to a new dimension/level. My guess is that the hive ejects bees based on conditions determined by its own level property but the bee reenters the hive base on conditions determined by its own level property. I also guess that the bees level property is not updated when a bee is transported to a new dimension/level and as a result the bee reenters it hive based on conditions in it birth level regardless of which dimension it is actually in. The level property seems to be out of sync between hives and bees that were born in another dimension/level. If this proves to be correct then it could be fixed by updating the level property of the bee to match that of the hive when it leaves or enters a hive. 

```java
Bee.level = Hive.level;
//then update nbt if needed
Bee.updateNBT();
```

Another possibility, this behavior might also occur if the compact machine dimension inherits the level properties of the level in which it was placed. I sort of doubt it since it never rains in compact machine world.

**Comment by TheCommensuratePup** [comment]
Can confirm this is also happening in my game as well. I am using compact machines too, if I set out side of the beehive and capture all of the bees & then reset their hive it will return them to normal operations. I have to capture them all before placing them down however, as just 2 or 3 doesn't do the job. There is a tiny window where the bee has exited but not returned that you can grab the bee. Only 1-3 frames though. 

Resetting the entire game, nor destroying & rebuilding the hive does not reset them.

**Comment by AmberFenix00** [comment]
Sorry, late response, but do you have something for them to do? such as pollenate flowers, or other materials? Not a creator of the mod, but I had the same issue, and that fixed it.

**Comment by TheCommensuratePup** [comment]
Yes, I have a 5x5 area directly below the beehive with the various blocks
required for said bee, eg quartz blocks, flowers, etc. If I take the
beehive & move it to the overworld it goes back to normal.

**Comment by Vivisectional** [comment]
I found out if you use a stick on the hive, the bees will be forced to exit, that will likely fix your issue.

**Comment by TheCommensuratePup** [comment]
Beet the bees! I tried and it worked for a bit but after an hour or so they were back to beeing stuck. I'll move them to the overworld and stop using compact machines till I get confirmation this bug is fixed.
-------- Original message --------From: AmberFenix00 ***@***.***> Date: 7/23/22  7:51 PM  (GMT-06:00) To: JDKDigital/productive-bees ***@***.***> Cc: TheCommensuratePup ***@***.***>, Comment ***@***.***> Subject: Re: [JDKDigital/productive-bees] [BUG] [1.18.1] Bees will leave the
  hive and immediately reenter repeating (Issue #248) 
I found out if you use a stick on the hive, the bees will be forced to exit, that will likely fix your issue.

**Comment by cholio** [comment]
Playing ATM7 (0.4.23) with Forge (40.1.60) and Productive Bee (0.9.0.9) on a decicated server i had been facing the same problem after updating atm7. 
updated productivebees manually to 0.9.10 as this problem was mentioned in the patchnotes.
now my bees are working as expected in "the end" 
only 5 min in game - will update if it should fall back to this in and out.
saved my day - thank you ;)

**Comment by JaisDK** [comment]
nice, thank you for testing it!
