### ISSUE TITLE
[suggestion] Use for honey

### ISSUE THREAD

**Issue by NightmareElmo** [JDKDigital/productive-bees#27]
I have a crapload of honey, and absolutely no use for it, I'd love to be able to use it somehow. Generating power from honey would be awesome but thats probably outside the scope of this mod. Maybe using honey as a hive accelerator or something? Honestly no clue, but some use for honey would be sweet. Loving this mod btw, definitely my new go-to resource generator

**Comment by JaisDK** [comment]
I hear you, between the hives and the centrifuge you end up with a lot of honey. I can't think of a use for it that would make sense withing the scope of this mod at this moment, but I am thinking to let the centrifuge operate without the use of bottles so it wont generate honey to at least limit the amount you get.
I am sure though that since honey is a new vanilla item, many mods will find a new use for it especially food mods.
I might have another use for it later when I implement a system for manipulating bee attributes, those bees need a reason to sit still.

I'm glad you like the mod :)

**Comment by NightmareElmo** [comment]
I agree about the centrifuge, it doesn't need to produce honey, especially since the hives already produce honey. Some way to upgrade the centrifuge would be fantastic too, I currently just have a torcherino torch cranking mine up, otherwise I'd have to run too many centrifuges

**Comment by JaisDK** [comment]
Sounds like the comb production is a little too good :)
I have plans to make a powered centrifuge running on FE (if another installed mod has power generation), but for now you can change the processing speed in the config if it's too slow for you.
