### ISSUE TITLE
[BUG] Bee Block Conversion Does NOT Work

### ISSUE THREAD

**Issue by DizzyDJW** [JDKDigital/productive-bees#299]
Version: 1.18.2-0.9.0.11

Title says it all. I've placed bees in a box where they are forced to fly over the block that is to be converted to get back from their "flower", it's been hours and nothing has happened.

I have 7 blocks of space.

A hive at one end, the "flower" at the other and the blocks to be converted in between. Multiple, for good measure.

Nothing.

Is this a well-known bug? Is there a fix?

**Comment by JaisDK** [comment]
The block conversion does not work the same as in Resourceful Bees, the bee has to pollinate the block the same way it does the flowers, it's not done when flying over it.
There is a bug however where all bees will share the same conversion recipes which I have fixed in the upcoming release. This might be why the bee is not converting the blocks.

**Comment by DizzyDJW** [comment]
Can this information be added to the guide in the next patch also?
I checked through the entire book and could find no info on Bee Conversion.
