### ISSUE TITLE
BUG? Silent's Mechanisms - Comb centrifuge recipes inconsistent or missing

### ISSUE THREAD

**Issue by NFinET** [JDKDigital/productive-bees#32]
Hi, love the mod.

When Silent's Mechanisms is installed which adds many modded metals and levels of processing (such as dusts and chunks) resource combs from this mod don't produce consistent materials. What I mean by this is that some combs when centrifuged produce resource chunks, while most produce dust (which is what I assume is the intended resource to be produced?). Additionally, iron combs produce nothing at all when Silent's Mechanisms is installed.

None of these issues are fixed if JAOPCA is installed as well, which I tried on the off chance that it might work, and then uninstalled it.

I attempted isolating the issue (it was discovered while trying to assemble a modpack) and it indeed still happens if the only mods installed are the following:
- Just Enough Items 6.0.0.4
- Productive Bees 0.1.10
- Silent Lib 4.6.3+55
- Silent's Mechanisms 0.7.2+52

I don't know if this issue is unique to the mod being combined with Silent's Mechanisms and its handling of metals, or if this issue exists with other mods that add modded materials and levels of processing.

Thank you for your time.

**Comment by JaisDK** [comment]
Hello, thank you for taking your time to investigate and report the issue.
I had a look at Silent's Mechanisms source code and the reason you are getting chunks for some of the recipes is because the author has listed chunks from his mod to be the same as dust aka added them both to the dusts tag. When I process the centrifuge recipe I just take the first item registered as a dust for that resource which will result in getting a silents_mechanisms chunk sometimes and a dust other times. If you install more mods that add their own dust version, you will start to see a great mix of different mods resources, but that's just how the new tag system works.

You can see the copper dust tag implementation here: https://github.com/SilentChaos512/Silents-Mechanisms/blob/1.15/src/main/resources/data/forge/tags/items/dusts/copper.json

The missing iron however is not because of this mod, I noticed it myself yesterday with a different iron dust provider. I will see if I can find a fix for that today.

**Comment by JaisDK** [comment]
The iron turned out to be a simple mistake in the recipe.

While investigating the chunks from Silent's Mechanisms I found a dupe bug, so enjoy that while it lasts ;)

**Comment by NFinET** [comment]
I see! Thank you, as a follow-up question, is there any way to manually force a specific item to be the output of the centrifuge recipes? Such as forcing them all to be the actual dust piles, or dusts from JAOPCA or a specific mod?

**Comment by JaisDK** [comment]
Unfortunately no, there's no good way in forge to extract the most desired item from the tag My mod picks the first item in the tag (better than random ;)) and I'm pretty sure JAOPCA does the same. 
You can route the output through something like the Mekanism Oredictionificator to get a specific item from a tag, it works pretty well.

**Comment by NFinET** [comment]
I see, well thank you very much for replying!
