### ISSUE TITLE
[1.19.2] timeInHive config option not affecting all bees.

### ISSUE THREAD

**Issue by ShinQdan** [JDKDigital/productive-bees#379]
I wanted to nerf the bees because I think they are OP, especially with chunk loading on a server (even 1 diamond bee left working for a day gives stacks of diamond combs for free - make a few of them and you are swimming in diamond the next day). So I checked the config for possible solutions and only found timeInHive option seem usefull in this case. But either I don't understand how this option actually works or it is not working properly. I set it to 1728000 (24h) because I assumed this would make bees without any upgrades make 1 comb a day (or 1 trip with more combs on higher productivity). But I found that only some bees are affected. I set up farm with some bees (Slimy Bee, ZomBee, Skeletal Bee, Iron Bee, Blazing Bee and vanilla bee) and found that different bees have different results: Slimy Bee made no combs (idk why, it was making them before), vanilla, Iron, Skeletal and ZomBee made a few (around 10 combs each) and Blazing Bee made ~3 STACKS of Blazing Combs. My friend also found Diamond Bee unaffected by this setting (made more than a stack in 24h). All the bees (except Diamond) in the experiment had traits as follows:
- Productivity: normal
- Weather tolerance: none
- Behavior: diurnal
- Endurance: normal
Is this setting not working properly or is it me misunderstanding how it works?
Also, are there any other ways to nerf the bees (reduce amount of combs produced)?

Steps to reproduce:
1. Change the timeInHive config option to 1728000.
2. Set up some hives with different bees with the same traits and similar amount of flowering blocks available.
3. Find the amount of combs produced very differen.

Expected behavior: 1-4 combs produced a day.

Versions:
- Minecraft: 1.19.2
- Forge: 43.2.8
- Productive Bees: 0.10.7.0

**Comment by JaisDK** [comment]
Hey,

If you want only a couple of combs per day then I don't really understand why you want the mod in the first place. In any case, instead of changing the timeInHive config (which will be removed in 1.20), you can change the individual production rates per bee. Everything is controlled with recipes so you just need to create a datapack with overwritten production recipes.
Here's the recipe for the slimy bee https://github.com/JDKDigital/productive-bees/blob/dev-1.18.2/src/main/resources/data/productivebees/recipes/bee_produce/slimy_bee.json
You can set the chance for the comb item to 1% for instance.
You can further decrease the output by changing the comb centrifuge recipe
https://github.com/JDKDigital/productive-bees/blob/dev-1.18.2/src/main/resources/data/productivebees/recipes/centrifuge/honeycomb_slimy.json

**Comment by ShinQdan** [comment]
Thanks for the advice on how to do it.
As for why I want to use this mod nerfed - I like the idea of bees making resources "out of thin air" and the genetics stuff but I don't want them to be a main source of those resources, just more of an additional boost.

**Comment by ShinQdan** [comment]
I managed to make the nerfs using datapack. Thanks for help.
