### ISSUE TITLE
[Help] Centrifuge liquid flow to next Centrifuge

### ISSUE THREAD

**Issue by Kiriao** [JDKDigital/productive-bees#419]
i realizes when i was setting up 2 different bee produce diffident liquid by product that the Centrifuge honey flow to the beside Centrifuge, that make my 2nd beehive can't Centrifuge blood comb to produce blood from evilcraft. can i disable that flowing of liquids from Centrifuge to Centrifuge?

**Comment by Legorfyr** [comment]
Nope, it's intentional. Bees that create diff liquid should have their own centrifuge in a closed system.

**Comment by JaisDK** [comment]
that's not the issue, the thing is that centrifuges automatically output fluids to any other fluid container placed next to them including other centrifuges
I'm not gonna change that though because it allows for a whole chain of centrifuges to be emptied from just one end and I won't disable that, so move your individual centrifuges away from the other ones instead.
