### ISSUE TITLE
Skeletal and ZomBees Spawning without Chunk Loading in insane numbers

### ISSUE THREAD

**Issue by MarcoPolo1893** [JDKDigital/productive-bees#421]
In the normal world there is a area roughly 1000x1000 blocks where insane amounts of Skeletal and Zombees spawned. 
The chunks aren´t chunkloaded and there are no advanced beehives placed there. I´m also the only one playing on this server.
In fact I haven´t been to that part of the map for a month. But now there are tens of thousands of Skeletal and ZomBees there.

Mod Version: 1.19.2-0.10.7.2

**Comment by JaisDK** [comment]
Skeletal Bees and ZomBees only spawn from empty unlit advanced beehives, so there must have been some of those loaded somewhere for quite some time. It's very likely that the hive is not where the bees are because the bees like to wander until they get into an unloaded chunk and they will all congregate there.

To kill them use there commands
`/kill @e[type=productivebees:configurable_bee, name="Skeletal Bee"]`
`/kill @e[type=productivebees:configurable_bee, name="ZomBee"]`
