### ISSUE TITLE
Farmer Bee not working correctly

### ISSUE THREAD

**Issue by Eydamos** [JDKDigital/productive-bees#423]
I'm playing the mod pack `FTB Presents Direwolf20 1.20` in version 1.0.0

This has `Productive Bees` in version 12.2.4
Also some mod I don't know the name of adds right click functionality for crops.

The farmer bee just breaks the crops without using the right click functionality.

Additionally I would expect the farmer bee to plant new crops but it just breaks them. There is also a collector bee in the hive collecting the resources and even though crops and seeds are in the hive the farmer bee still does not try to plant new crops.

**Comment by JaisDK** [comment]
The farmer bee doesn't replant, it tries to right click harvest if a known right click harvest mod is installed. If they have a new mod or adds that functionality through another method like KubeJS, then they have to change the config to force the farmer bee to always try right click instead of breaking the crop. The config is in `/world/serverconfig/productivebees-server.toml` and is called `forceEnableFarmerBeeRightClickHarvest`

**Comment by Eydamos** [comment]
Setting the config to true helped.

I thought the farmer bee would also replant crops if it does not use the right click functionality.
The pages in the book for collector and hoarder bee mention that together with the farmer bee it would be an automated farm which is not true if no mod is installed that adds right click functionality.

I would suggest to either add replanting ability to the bee or change the book entries so that they mention that it is only an automated farm if right click functionality is enabled
