### ISSUE TITLE
Problem with bee showing (REI)

### ISSUE THREAD

**Issue by EnderCat263** [JDKDigital/productive-bees#454]
Minecraft version: 1.20.1
Mod version: productivebees-1.20.1-12.2.11
REI version: RoughlyEnoughItems-12.0.665

I have a problem with some bees (they are don't showing in REI) and it's very bad, because i cant find bee and what it's  producing and how bread it

**Comment by JaisDK** [comment]
do you have MCA installed?

**Comment by EnderCat263** [comment]
> do you have MCA installed?

No

**Comment by JaisDK** [comment]
then I'm gonna need a log from you

**Comment by EnderCat263** [comment]
> then I'm gonna need a log from you

latest?

**Comment by EnderCat263** [comment]
if latest, that it's:
[latest.log](https://github.com/JDKDigital/productive-bees/files/13891675/latest.log)

**Comment by JaisDK** [comment]
do the combs and spawn eggs show up?

**Comment by EnderCat263** [comment]
> do the combs and spawn eggs show up?

Spawn eggs yes, some combs also

**Comment by Alaric323** [comment]
I can confirm this issue, a decent chunk of bees are missing in REI.  My REI version is latest (12.0.684), and Productive Bees is also latest (1.20.1-12.2.15).  I do not have any datapacks creating or removing bees.  A screenshot of the list of bees available for me to see is below:

![image](https://github.com/JDKDigital/productive-bees/assets/4038592/ddd8d6d3-d4ff-491d-865c-5acd5eb5b572)

Of note is that even the vanilla bee is missing, so while bees ARE inside the hives, they do not appear when opening the GUI.  This makes it difficult to even get started, or use the simulation + babee modules to know what is being bred.

![image](https://github.com/JDKDigital/productive-bees/assets/4038592/16d90642-b188-4b84-9e4c-b91b17c85666)

**Comment by JaisDK** [comment]
Are you sure it’s REI causing it? What other mods do you have? Have you tried with JEI instead to see if it’s the same issue? Is this single player or server?

**Comment by Alaric323** [comment]
JEI DOES have a fuller, if not full, list of bees including the vanilla bee.
JEI List:
![image](https://github.com/JDKDigital/productive-bees/assets/4038592/e4ddae15-d21d-4002-b119-2dfb8140b163)
JEI Hive:
![image](https://github.com/JDKDigital/productive-bees/assets/4038592/7654fa92-074a-4a0d-994d-09927cf264e5)

This is on a self hosted server (a slightly modified pack of MineColonies: Dimensional Adventures), but the same thing occurs in singleplayer.  The only difference between these images and the previous ones are disabling REI and enabling JEI (which the pack initially came with, but I switched due to it's more modern config and layout).

**Comment by JaisDK** [comment]
It’s sometimes to report to REI then
