### ISSUE TITLE
Bees don't go in the hive when i try putting them in.

### ISSUE THREAD

**Issue by Dado34** [JDKDigital/productive-bees#463]
When i try to put the bees in the hive they don't get in and i don'know what to do. Im trying to play the "All the mods 9" mod pack. Any help is really appreciated.

**Comment by JaisDK** [comment]
what do you mean by trying "putting them in"
bees go into the hive on their own if they've pollinated on a valid block so make sure you have the correct flowering block for them (you can see that in JEI)

what's more likely to be your problem, since you're new to the mod, is that you've collected solitary bees which do not go into hives, they only live in solitary nests

**Comment by Dado34** [comment]
I have tried with vanilla bees and when i crouch and right click the bees dont go in the nest, am i  doing it wrong?

**Comment by Dado34** [comment]
Sorry if i dont explain myself properly, im Italian and not really used to write in english. I may also dont get what you are saying sometimes. Sorry.

**Comment by JaisDK** [comment]
vanilla bees need flowers, once they've pollinated, they will look for a hive to move into
build an enclosure around the hive and bees so they don't fly away, their pathing and AI is pretty stupid at times

**Comment by Dado34** [comment]
ok I will try ty

**Comment by Dado34** [comment]
I think i solved thank you.
