### ISSUE TITLE
Wood Chips Server Crash

### ISSUE THREAD

**Issue by WenXin20** [JDKDigital/productive-bees#51]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Productive Bees v0.1.15`
`JEI v6.0.2.12`

My server crashed after clicking on a Wood Chip in JEI's cheat mode.
[Crash Report](https://gist.github.com/WenXin20/c078a8d7794687ea9989eac49af3c58c)

**Comment by JaisDK** [comment]
Can you tell me which wood chip JEI is displaying? I think it can vary every time you load up the game and some wood types might cause problem.

**Comment by JaisDK** [comment]
It's only showing one wood chip item which is useless. I'll make sure it shows all of them in the next update. You can get each variant in the creative menu though.

**Comment by WenXin20** [comment]
It was a Enigma Log wood chips from the Pokecube AIO mod.-----------------------Sincerely, David NewvilleOn Jul 23, 2020 5:08 PM, Jais Djurhuus-Kempel <notifications@github.com> wrote:
Can you tell me which wood chip JEI is displaying? I think it can vary every time you load up the game and some wood types might cause problem.

**Comment by WenXin20** [comment]
And the Wood Chip from the Fruit Trees mod is invisible.

**Comment by JaisDK** [comment]
Some wood blocks are rendered differently unfortunately so I've left them invisible until I figure out what to do about them.

I figured out the problem with the crash. The method I am using the get the name of the wood block to put in the name of the wood chip is a client only method, so when used on a server it crashes.
The reason the server is trying to get the name is because JEI is adding the item name to the chat.

Thanks for your help, I'll get it fixed in the next version.

**Comment by WenXin20** [comment]
Thanks!
