### ISSUE TITLE
Exessive amount of bee's spawning

### ISSUE THREAD

**Issue by Darkere** [JDKDigital/productive-bees#59]
Not entirely certain how this happens but: 
![image](https://user-images.githubusercontent.com/4283717/89046935-f84d9d00-d34d-11ea-8555-fa386b120401.png)
![image](https://user-images.githubusercontent.com/4283717/89046946-fbe12400-d34d-11ea-86be-2b031f4b628b.png)
![image](https://user-images.githubusercontent.com/4283717/89046959-ff74ab00-d34d-11ea-8a5f-ff850430b68c.png)

Pack Enigmatica 6
Forge: 32.0.75
productivebees-1.16.1-0.1.15.2.jar

**Comment by minecrafterseppe** [comment]
the hives spawn the bees and the bees fly off to unloaded chunks
and then the hives spawn more endlesly

**Comment by MathiasDeWeerdt** [comment]
I'd add to this: Bees from the nether are a pain to find to took me over 3 hours to find one nest!

**Comment by JaisDK** [comment]
The problem is not that they abandon their nests (except if there's no flowers nearby), but the solitary bees lay eggs and have offspring leaving more bees than there are nests. These extra bees then fly off to unloaded chunks and you find a wall of them when you go exploring. I have a note to kill off bees who don't find a nest to live in within a certain time.

@MathiasDeWeerdt the nether quartz nests are extremely hard to find because they spawn underground instead of on the surface, I also have a note to look into that. You can however make the nests yourself and place them in the nether, after 30 minutes a new bee will move in as long as it is chunkloaded.

**Comment by JaisDK** [comment]
Added a 10 minute lifespan to solitary bees without nests in 0.2.2
