### ISSUE TITLE
Iron bees aren't producing anything and leaving the advanced oak beehive.

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [JDKDigital/productive-bees#60]
Iron bees don't produce and don't get into the advanced oak beehives.
I tried in a single-player world and confirmed this. The exact same setup with copper bees does work perfectly.

When they do get into it, they get out immediately after and leave some sort of "ghost" bee inside which only updates the UI if i withdraw the glass bottles.

**Comment by MathiasDeWeerdt** [comment]
Reading the code i'd need a ferric type flower?

**Comment by MathiasDeWeerdt** [comment]
Placing iron ore around the advanced oak beehive seems to be working, but what flower could I use?

**Comment by WhitePhant0m** [comment]
"minecraft:iron_ore",
        "minecraft:iron_block",
        "minecraft:iron_bars",
        "minecraft:iron_door",
        "minecraft:iron_trapdoor",
        "minecraft:cauldron",
        "minecraft:hopper"
These count as ferric flowers

**Comment by JaisDK** [comment]
There are no actual iron flowers right now, I am experimenting with different "flower" requirements for some of the bees which is why copper bees will still just use normal flowers.

The ghost bee should also disappear if you close the gui and open it again. There are still some gui issues in the 1.16.1 version since that code changed from 1.15.2.

The general rule is that iron bees need something made of iron (the ones mentioned above), gold bees needs something gold, redstone bees needs something redstone (dust, block torch, lamp), glowing bee needs glowstone or shroomlight.

**Comment by JaisDK** [comment]
The vanilla handling of not having a flower nearby is really bad so I might implement my own handler that doesn't make the bee fly around forever like an idiot.
