### ISSUE TITLE
Suggetion 1.16.1 | Compatibility with beenfo

### ISSUE THREAD

**Issue by plenet10** [JDKDigital/productive-bees#65]
Hi,

I have a server on forge version 32.0.98 and in my server logs every time I click on a beehive/Nest. I get a small error that the mod Beenfo cant access the data in Hive/Nest. I was wondering if this is an issue on the side of Productive Bees or on the side of Beenfo. Perhaps compatibility can be added? If more info is needed please ask.

[](https://pastebin.com/XRSK8VWE)

**Comment by plenet10** [comment]
[Link to Pastbin](https://pastebin.com/XRSK8VWE)

**Comment by JaisDK** [comment]
Hi, 
The problem is in Beenfo as they assume all BeehiveTileEntities have the HONEY_LEVEL blockstate property, they should really do a check if the blockstate exists instead of relying on the TE type.
It was probably working with Productive Bees until recently as I removed that property from Nests in v0.2

**Comment by plenet10** [comment]
Great thanks for the response I will close this issue and ask the beenfo devs if they will add compatibility or just turn of the server log spam...
